### ISSUE TITLE
launcher is showing "install" instead of "update" even after downloading the game

### ISSUE THREAD

**Issue by HG07-YS** [ScottMichaud/YandereSimulatorLauncher2#20]
Even after downloading the game in the launcher it shows "install" instead of "checking for updates" pls I hope you fix this

**Comment by ScottMichaud** [comment]
The launcher looks for a file called YandereSimulator.exe in a folder called YandereSimulator that is in your working folder (which is the folder that YandereSimulatorLauncher2.exe is run from).

If it cannot find (folder with YandereSimulatorLauncher2.exe)/YandereSimulator/YandereSimulator.exe, then it asks you to install it.

_**You must extract YandereSimLauncher.zip into a folder that you have full control over (such as Desktop, Downloads, Documents, or a USB removable drive) and run YandereSimulatorLauncher2.exe from that new folder.**_ If you run a .exe from within a ZIP file, then Windows will have its working folder be inside the Windows Temporary Files folder, and the launcher will likely show the Install button when it's restarted (because the game was installed into the temporary files folder).

This is covered in #3.

**Comment by ScottMichaud** [comment]
2.9.0 attempts to add a warning if you run from the temporary files folder.
